### ISSUE TITLE
KeyError: 'mix'

### ISSUE THREAD

**Issue by AltamarMx** [brandonbondig/growatt-api#1]
When trying mix_ids
mix_ids = api.get_mix_ids(plant_id)
mix_ids

i get:

------------------------------------------------------------
KeyError                   Traceback (most recent call last)
Cell In[4], line 1
----> 1 mix_ids = api.get_mix_ids(plant_id)
      2 mix_ids

File ~\venvs\inversores\Lib\site-packages\growatt\__init__.py:155, in Growatt.get_mix_ids(self, plantId)
    152 res.raise_for_status()
    154 try:
--> 155     json_res = res.json()['obj']["mix"]
    157     if not json_res:
    158         raise ValueError("Empty response. Please ensure you are logged in.")

KeyError: 'mix'

**Comment by brandonbondig** [comment]
It seems to work on my end 
```python
from growatt import Growatt

api = Growatt()
api.login("email","password")

plant_id = api.get_plants()[0]["id"]

mix_ids = api.get_mix_ids(plant_id)

print(mix_ids)
```


Could you provide the script you've written?

**Comment by AltamarMx** [comment]
This is the script, the simplest one! 

```python 
from growatt import Growatt

api = Growatt()
api.login("XXX","XXX")

plant_id = api.get_plants()[0]["id"]

mix_ids = api.get_mix_ids(plant_id)

print(mix_ids)
```
And i get:

```bash
Traceback (most recent call last):
  File "C:\Users\gbv\tableros_inversores\notebooks\mix.py", line 8, in <module>
    mix_ids = api.get_mix_ids(plant_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gbv\venvs\inversores\Lib\site-packages\growatt\__init__.py", line 155, in get_mix_ids
    json_res = res.json()['obj']["mix"]
               ~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'mix'
```

I can see the list of plants, so i am logged in.

On the Growatt page, i can see the plant, the devices, and with the API i can see the plants but no the devices... i am missing something ? 

thanks!

**Comment by brandonbondig** [comment]
Could you provide the output of this:

```python
plant_id = api.get_plants()
```

Of course with the real values obfuscated

**Comment by AltamarMx** [comment]
I realized that my plants have no hybrid devices, so, they dont exist. I am new in growatt, bu so thankful for your time.

**Comment by brandonbondig** [comment]
Ah i see, no problem.
